class Privilege():
    _allowed_object_type = ["USER","ROLE","WAREHOUSE","DATABASE","SCHEMA","TABLE","FILE FORMAT","PIPE","TASK","STAGE","STREAM"]
    _allowed_privileges = {
        "USER": ["MONITOR","OWNERSHIP","ALL"],
        "ROLE": ["OWNERSHIP"],
        "STAGE":["READ","WRITE","OWNERSHIP"],
        "WAREHOUSE": ["APPLYBUDGET","MODIFY","MONITOR","OPERATE","USAGE","OWNERSHIP","ALL"],
        "DATABASE": ["APPLYBUDGET","MODIFY","MONITOR","USAGE","REFERENCE_USAGE","CREATE DATABASE ROLE","CREATE SCHEMA","IMPORTED PRIVILEGES","OWNERSHIP","ALL"],
        "SCHEMA": ["APPLYBUDGET","MODIFY","MONITOR","USAGE","CREATE AUTHENTICATION POLICY","CREATE DATA METRIC FUNCTION","CREATE TABLE","CREATE DYNAMIC TABLE","CREATE EVENT TABLE",
                          "CREATE EXTERNAL TABLE","CREATE GIT REPOSITORY","CREATE ICEBERG TABLE","CREATE VIEW","CREATE MASKING POLICY","CREATE MATERIALIZED VIEW","CREATE NETWORK RULE",
                          "CREATE NOTEBOOK","CREATE ROW ACCESS POLICY","CREATE SECRET","CREATE SESSION POLICY","CREATE STAGE","CREATE STREAMLIT","CREATE FILE FORMAT",
                          "CREATE SEQUENCE","CREATE FUNCTION","CREATE PACKAGES POLICY","CREATE PASSWORD POLICY","CREATE PIPE","CREATE STREAM","CREATE TAG","CREATE TASK","CREATE PROCEDURE",
                          "CREATE ALERT","CREATE CORTEX SEARCH SERVICE","CREATE SNOWFLAKE.CORE.BUDGET","CREATE SNOWFLAKE.DATA_PRIVACY.CLASSIFICATION_PROFILE","CREATE SNOWFLAKE.DATA_PRIVACY.CUSTOM_CLASSIFIER",
                          "CREATE SNOWFLAKE.ML.ANOMALY_DETECTION","CREATE SNOWFLAKE.ML.CLASSIFICATION","CREATE SNOWFLAKE.ML.FORECAST","CREATE SNOWFLAKE.ML.TOP_INSIGHTS","CREATE SNOWFLAKE.ML.DOCUMENT_INTELLIGENCE",
                          "CREATE MODEL","CREATE MODEL MONITOR","CREATE IMAGE REPOSITORY","CREATE SERVICE","CREATE SNAPSHOT","ADD SEARCH OPTIMIZATION","OWNERSHIP","ALL"],
        "TABLE": ["SELECT","INSERT","UPDATE","TRUNCATE","DELETE","EVOLVE SCHEMA","REFERENCES","APPLYBUDGET","OWNERSHIP","ALL"],
        "FILE FORMAT": ["USAGE","OWNERSHIP","ALL"],
        "PIPE": ["APPLYBUDGET","MONITOR","OPERATE","OWNERSHIP","ALL"],
        "STREAM":["SELECT","OWNERSHIP","ALL"],
        "TASK": ["APPLYBUDGET","MONITOR","OPERATE","OWNERSHIP","ALL"]
    }