APP_TITLE = 'Snowchain'
SHOVELING = 'shoveling ...'
HANG_ON = 'Hang on tight, I am on it ...'

ROLE = 'role'
USER = 'user'
TEXT = 'text'
TOOLS = 'tools'
OUTPUT = 'output'
CONTENT = 'content'
MESSAGE = 'message'
MESSAGES = 'messages'
ASSISTANT = 'assistant'
INITIALIZED = 'initialized'
CHAT_HISTORY = 'chat_history'

#SF objects
USER_OBJ = 'user'
ROLE_OBJ = 'role'
TASK_OBJ = 'task'
TABLE_OBJ = 'table'
SHARE_OBJ = 'share'
SCHEMA_OBJ = 'schema'
ACCOUNT_OBJ = 'account'
DATABASE_OBJ = 'database'
WAREHOUSE_OBJ = 'warehouse'
FILEFORMAT_OBJ = 'fileformat'
INTERNAL_STAGE_OBJ = 'internalstage'
EXTERNAL_STAGE_OBJ = 'externalstage'
RESOURCE_MONITOR_OBJ = 'resourcemonitor'