_name_label = 'NAME'
_type_label = 'TYPE'
_size_label = 'SIZE'
_auto_resume_label = 'AUTO_RESUME'
_auto_suspend_label = 'AUTO_SUSPEND'
_comment_label = 'COMMENT'
_enable_query_acceleration_label = 'ENABLE_QUERY_ACCELERATION'
_initially_suspended_label = 'INITIALLY_SUSPENDED'
_max_cluster_count_label = 'MAX_CLUSTER_ACCOUNT'
_resource_constraint_label = 'RESOURCE_CONSTRAINT'
_max_concurrency_level_label = 'MAX_CONCURRENCY_LEVEL'
_min_cluster_count_label = 'MIN_CLUSTER_COUNT'
_query_acceleration_max_scale_factor_label = 'QUERY_ACCELERATION_MAX_SCALE_FACTOR'
_resource_monitor_label = 'RESOURCE_MONITOR'
_scaling_policy_label = 'SCALING_POLICY'
_statement_timeout_in_seconds_label = 'STATEMENT_TIMEOUT_IN_SECONDS'
_statement_queued_timeout_in_seconds_label = 'STATEMENT_QUEUED_TIMEOUT_IN_SECONDS'
_tag_label = 'TAG'
_allowed_values_type =['STANDARD','SNOWFLAKE-OPTIMIZED']
_allowed_values_wh_snowpark_optimized =['XSMALL','SMALL','MEDIUM','LARGE','XLARGE','XXLARGE','XXXLARGE','X4LARGE']
_allowed_values_wh_standard = ['XSMALL','SMALL','MEDIUM','LARGE','XLARGE','XXLARGE','XXXLARGE','X4LARGE','X5LARGE','X6LARGE']
_allowed_values_enable_query_acceleration = ['TRUE','FALSE']