APP_TITLE = 'Snowchain'
SHOVELING = 'shoveling ...'
HANG_ON = 'Hang on tight, I am on it ...'

ROLE = 'role'
USER = 'user'
TEXT = 'text'
TOOLS = 'tools'
OUTPUT = 'output'
CONTENT = 'content'
MESSAGE = 'message'
MESSAGES = 'messages'
ASSISTANT = 'assistant'
INITIALIZED = 'initialized'
CHAT_HISTORY = 'chat_history'
CHAT_DISABLED = 'chat_disabled'

#SF objects
USER_OBJ = 'user'
ROLE_OBJ = 'role'
TASK_OBJ = 'task'
ALERT_OBJ = 'alert'
TABLE_OBJ = 'table'
SHARE_OBJ = 'share'
STREAM_OBJ = 'stream'
SCHEMA_OBJ = 'schema'
ACCOUNT_OBJ = 'account'
COPYINTO_OBJ = 'copyinto'
SNOWPIPE_OBJ = 'snowpipe'
DATABASE_OBJ = 'database'
WAREHOUSE_OBJ = 'warehouse'
FILEFORMAT_OBJ = 'fileformat'
COPY_HISTORY_OBJ = 'copyhistory'
NOTIFICATION_OBJ = 'notification'
MASKING_POLICY_OBJ = 'maskingpolicy'
INTERNAL_STAGE_OBJ = 'internalstage'
EXTERNAL_STAGE_OBJ = 'externalstage'
RESOURCE_MONITOR_OBJ = 'resourcemonitor'